### ISSUE TITLE
Line breaks in a string

### ISSUE THREAD

**Issue by Withered-Flower-0422** [JoeStrout/miniscript#128] opened 2024-02-11 16:40 UTC
In MM editor:
```
a = "123
456
789"

print a
```
And the result comes:
```
123
456
789
```

This should be better to throw an error.

And this also relates to the wrong line reporting.

See on [Discord](https://discord.com/channels/646000428441534474/646000428441534478/1206272754983239762).

**Comment by MineRobber9000** [comment] 2024-02-11 21:20
What exactly is the intended behavior of newlines in a string? One of the things I dislike about MiniScript strings is that they have no escapes (i.e; any character you want to represent in the string *must* be directly input in the string). Allowing newlines within the string literal (which the current parser code does by virtue of just not checking for them) allows for relatively painless multiline strings:

```
helpMessage = "Usage: ./foo.ms <bar> [baz]

Foos a bar, and additionally a baz.

Arguments:
 - bar: Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.
 - baz: Most lorem ipsum text begins with the classic 5 word sequence ""lorem ipsum dolor sit amet"", before continuing on with random Latin words that don't mean anything in the order they're given."
```

Compare to what you'd have to do if this were not allowed:

```
helpMessage = "Usage: ./foo.ms <bar> [baz]"+char(13)+char(13)+"Foos a bar, and additionally a baz."+char(13)+char(13)+"Arguments:"+char(13)+" - bar: Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups."+char(13)+" - baz: Most lorem ipsum text begins with the classic 5 word sequence ""lorem ipsum dolor sit amet"", before continuing on with random Latin words that don't mean anything in the order they're given."
```

That's just ugly. Also, compare to other programming languages, such as Python:

```python
helpMessage = """Usage: ./foo.py <bar> [baz]

Foos a bar, and additionally a baz.

Arguments:
 - bar: Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.
 - baz: Most lorem ipsum text begins with the classic 5 word sequence "lorem ipsum dolor sit amet", before continuing on with random Latin words that don't mean anything in the order they're given."""

# or even if we're not allowed to use multiline syntax:

helpMessage = "Usage: ./foo.ms <bar> [baz]\n\nFoos a bar, and additionally a baz.\n\nArguments:\n - bar: Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.\n - baz: Most lorem ipsum text begins with the classic 5 word sequence \"lorem ipsum dolor sit amet\", before continuing on with random Latin words that don't mean anything in the order they're given."
```

IMO, the better option would be to embrace embedded newlines in strings. I already have a patch ready for PR that would make both C# and C++ versions of MiniScript advance the line number when the string literal contains a newline (the downstream ports would need to follow along, but it's not really that hard, and I could probably PR to the ports that are 1:1 with the reference implementation anyways).

**Comment by JoeStrout** [comment] 2024-02-11 23:50
Yes, this is a bug in the parser (technically, the lexer) when taking source code as a file.  It occurs in both C++ and C#.  The REPL (again, in both cases) handles it correctly, with a "missing close quote" error.

Via Discord, we did have an extensive and enthusiastic discussion of the pros and cons of officially supporting multiline string literals.  The participants were split on whether such a feature is desirable, for various reasons.  On the whole I've decided they are more trouble than its worth.

So, the original bug report above is right — these should throw a runtime error even in a file, just like they do on the REPL.

**Comment by MineRobber9000** [comment] 2024-02-12 00:12
Summarizing my points from the extended discussion in Discord here (mainly to get them into a public forum and out of my head):

- Multiline strings are important; there's a reason so many languages include syntax for them
- Strings in MiniScript function on a "the characters in a string are the characters in the string" principle; if you want, say, an emoji in your string, you put an emoji in your string.
- By that logic, if you put a newline in your string, you should get a newline in your string.
- Problems:
    - What does the newline entail? Do we keep system representation or do we canonicalize to something?
      - I argued initially in favor of leaving it, but after studying Lua and Python's behavior around it, decided to agree on `\n` as a universal newline
    - The parser will give unhelpful errors if you forget to close a string as opposed to erroring outright
      - The parser *already* gives unhelpful errors throughout (it took rubber-ducking my code to realize I had forgotten the space in `end if`)
      - We can have a whole argument over how to make the parser errors more helpful (the best parser I've ever seen in terms of helpful error messages was [urn](https://urn-lang.com/), a lisp, which helpfully suggests ways to fix certain syntax errors), but that's kind of out of scope for "should we support multiline strings"
    - Syntax highlighters will bug out if we forget to close a string
      - I personally don't think "if you feed malformed data into a syntax highlighter it spits out malformed output" is an issue; most editors I've seen have a delay between "you stop typing" and "the highlighter highlights", so if you forget the close quote you'll notice when the entirety of the next half of the file is highlighted as a string
      - Even if it's a problem, other languages have multiline string syntax and their syntax highlighters handle it just fine
    - It was never intended to allow that use, the lexer is just bugged
      - The string lexer was checked into the GitHub repo 5 years ago (I checked for the sake of this comment because I didn't want to be That Guy:tm: more than I already am being That Guy:tm:), and at no point was "string without a closing quote should error at the newline" added to the unit tests. 5 years (presumably 7, going all the way back to MiniScript 1.0, though I don't have access to MiniScript releases going that far back to check) of the lexer being "bugged" and there was never a check to make sure that the lexer was working as intended?
      - There's no doubt code in the wild that expects these strings with newlines in them to work; I assumed it was a feature when I was porting the lexer to Lua.
      - Additionally (and this just occurred to me recently), we shouldn't introduce such breaking behavior in 1.6.2, which is supposed to be a *patch* release. If we wanted to change this for 2.0 (or even 1.7, since MiniScript seems to be using minor as major until the Eventual:tm: MiniScript 2.0), I'd be all for it, but making a breaking change in a patch release just seems like a terrible idea to me.
- Possible other solutions:
    - Use `list.join` to combine a string for each line/use `string.replace` to replace sentinels for newlines/use one of the object-notation stdlib functions to parse escape codes
      - It's ugly (to borrow my own turn of phrase from above). Again, any other character can be put in a string without issue; why should I need to use a different function entirely just because I want specifically newlines?
    - Split the string on newlines as `"foo"+char(10)+"bar"`
      - Ugly. Awful. I hate it. I'd rather (ab)use `list.join` or `string.replace` or the stdlib functions.

**Closed** 2024-02-17 22:28 UTC
