### ISSUE TITLE
Unmatched "end if" should throw a compiler error

### ISSUE THREAD

**Issue by Andreyul** [JoeStrout/miniscript#46] opened 2020-10-11 00:13 UTC
**Steps to Reproduce**:

Compile:
```
end if
```

**Actual result**: Compiles successfully
**Expected result**: Compiler Error: 'end if' without matching 'if'

**Comment by JoeStrout** [comment] 2020-10-11 21:51
I'm unable to reproduce this one in either the C++ (command-line) or the C# (Mini Micro) environments.

```
MiniScript 
Command-Line (Unix) v1; language v1.5 (Aug 19 2020)
> end if
Compiler Error: 'end if' without matching 'if' [line 1]
```

Possibly this is something already fixed?  Closing this for now, but we'll open it back up again if you can point out a way I can reproduce it.

**Closed by JoeStrout** 2020-10-11 21:51 UTC

**Comment by Andreyul** [comment] 2020-10-11 22:09
Reproducible at https://miniscript.org/tryit/
