### ISSUE TITLE
Exponential operations should be performed from right to left

### ISSUE THREAD

**Issue by Withered-Flower-0422** [JoeStrout/miniscript#178] opened 2024-08-03 17:58 UTC
MiniScript:
```
> 3^3^3
19683
>
```
Python:
```
>>> 3**3**3
7625597484987
>>>
```
JavaScript:
```
> 3**3**3
7625597484987
>
```
Lua:
```
> 3^3^3
7625597484987.0
>
```
Also mathematically speaking, exponential operations should be performed from right to left.

**Comment by JoeStrout** [comment] 2024-08-03 23:05
Closing as duplicate of #172.

**Closed by JoeStrout** 2024-08-03 23:05 UTC
