### ISSUE TITLE
Bugs with `funcRef`

### ISSUE THREAD

**Issue by Withered-Flower-0422** [JoeStrout/miniscript#136] opened 2024-02-19 17:16 UTC
MM:
```
]funcRef.f = function; print "hi"; end function
](@print).f
hi
```
CL:
```
> funcRef.f = function; print "hi"; end function 
> (@print).f
Runtime Error: Key Not Found: 'f' not found in map [line 1]
```
See on [Discord](https://discord.com/channels/646000428441534474/646000428441534478/1209169282173247498).

And:
```
]funcRef.f = 42
]a = function; end function
](@a).f
42
](@globals.a).f
Runtime Error: Type Error (while attempting to look up f) [line 1]
```
See on [Discord](https://discord.com/channels/646000428441534474/646000685065830420/1209184543353868298).

**Comment by juh9870** [comment] 2024-02-19 18:44
This is not a unique to `funcRef`. Duplicate of #70

**Comment by Withered-Flower-0422** [comment] 2024-02-21 15:48
OK, the issue is already reported in #99.

**Closed** 2024-02-21 15:48 UTC
